name: "My Shell Action"
description: "A GitHub Action that uses shell commands and sets an output value"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
    value: ${{ steps.set-output.outputs.greeting }}  # Referencing the output value from a step    
runs:
  using: "composite"
  steps:
    - id: set-output  # Assign an ID to the step
      run: |
        echo "Hello, ${{ inputs.name }}!"
        # Create a greeting message
        GREETING="Hello, Miss ${{ inputs.name }}! Welcome to GitHub Workflows."
        # Set the output variable
        echo "greeting=$GREETING" >> $GITHUB_OUTPUT
      shell: bash  
    - name: Set up Maven cache 1
      id: cache-maven1
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-
        restore-keys: |
          ${{ runner.os }}-maven-         
