name: "Test My Shell Action"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Shell Action
        id: myaction
        uses: ./
        with:
          name: "GitHub User"

      - name: Use output from My Shell Action
        run: "echo 'The greeting message is: ${{ steps.myaction.outputs.greeting }}'"
